# Generated by Django 5.1.7 on 2025-03-17 21:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('token_name', models.CharField(blank=True, max_length=100, null=True)),
                ('token_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('token_supply', models.BigIntegerField(default=0)),
                ('token_contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_network', models.CharField(default='sei', max_length=50)),
                ('owner_wallet_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('token_balance', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.project')),
            ],
            options={
                'unique_together': {('project', 'external_id')},
            },
        ),
    ]
