# Generated by Django 5.1.7 on 2025-03-31 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_current_hash_key_hashkeyrotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashkeyrotation',
            name='previous_hash_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hashkeyrotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_keys', to='users.appuser'),
        ),
    ]
