# Generated by Django 5.1.7 on 2025-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_hashkeyrotation_previous_hash_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashkeyrotation',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hashkeyrotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hashkeyrotation',
            name='previous_hash_key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
