# Generated by Django 5.1.7 on 2025-03-28 04:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_appuser_current_hash_key_hashkeyrotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('tokens_earned', models.DecimalField(decimal_places=8, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='users.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='TokenizationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('purchase', 'Purchase'), ('video_watch', 'Video Watch'), ('profile_completion', 'Profile Completion'), ('custom', 'Custom Action')], max_length=50)),
                ('custom_action_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('cooldown_hours', models.FloatField(blank=True, null=True)),
                ('cooldown_minutes', models.FloatField(blank=True, null=True)),
                ('one_time', models.BooleanField(default=False)),
                ('multiplier', models.FloatField(blank=True, null=True)),
                ('min_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenization_rules', to='users.project')),
            ],
            options={
                'unique_together': {('project', 'action_type', 'custom_action_name')},
            },
        ),
    ]
