# Generated by Django 5.1.7 on 2025-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizationrule',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the tokenization rule'),
        ),
    ]
