# Generated by Django 5.1.7 on 2025-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0002_tokenizationrule_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_standard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
