# Generated by Django 5.1.7 on 2025-04-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0003_actiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizationrule',
            name='code_snippet_html',
            field=models.TextField(blank=True, help_text='HTML/jQuery code snippet for implementing this rule'),
        ),
        migrations.AddField(
            model_name='tokenizationrule',
            name='code_snippet_js',
            field=models.TextField(blank=True, help_text='JavaScript code snippet for implementing this rule'),
        ),
        migrations.AddField(
            model_name='tokenizationrule',
            name='code_snippet_react',
            field=models.TextField(blank=True, help_text='React code snippet for implementing this rule'),
        ),
    ]
