# Generated by Django 5.1.7 on 2025-04-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0004_tokenizationrule_code_snippet_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizationrule',
            name='code_snippet_sdk',
            field=models.TextField(blank=True, help_text='Link3 SDK initialization code snippet'),
        ),
    ]
