# Generated by Django 5.1.7 on 2025-03-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('users', '0002_appuser_current_hash_key_hashkeyrotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenredemption',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='tokenredemption',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RemoveField(
            model_name='tokenredemption',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tokenredemption',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenredemption',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='tokenredemption',
            index=models.Index(fields=['user'], name='blockchain__user_id_a41876_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenredemption',
            index=models.Index(fields=['status'], name='blockchain__status_9be0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenredemption',
            index=models.Index(fields=['created_at'], name='blockchain__created_e16852_idx'),
        ),
    ]
