# Generated by Django 5.1.7 on 2025-04-20 18:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_tokenredemption_options_and_more'),
        ('users', '0004_hashkeyrotation_last_used_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chain_id', models.CharField(max_length=50)),
                ('rpc_endpoint', models.URLField()),
                ('explorer_url', models.URLField(blank=True, null=True)),
                ('is_testnet', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['chain_id'], name='blockchain__chain_i_c2ace0_idx'), models.Index(fields=['is_active'], name='blockchain__is_acti_ca75da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('contract_address', models.CharField(blank=True, max_length=100, null=True)),
                ('decimals', models.IntegerField(default=18)),
                ('total_supply', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('is_deployed', models.BooleanField(default=False)),
                ('admin_address', models.CharField(max_length=100)),
                ('creation_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='blockchain.blockchainnetwork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('MINT', 'Mint'), ('REDEMPTION', 'Redemption'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('wallet_address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.projecttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='users.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_message', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='blockchain.blockchainnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='users.appuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='projecttoken',
            index=models.Index(fields=['project'], name='blockchain__project_e8b7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttoken',
            index=models.Index(fields=['is_deployed'], name='blockchain__is_depl_02fc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttoken',
            index=models.Index(fields=['contract_address'], name='blockchain__contrac_a12856_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttoken',
            unique_together={('project', 'network', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['user'], name='blockchain__user_id_06bf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['project_token'], name='blockchain__project_d90947_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['status'], name='blockchain__status_a844b7_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['transaction_type'], name='blockchain__transac_b26501_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['created_at'], name='blockchain__created_be28c6_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['user'], name='blockchain__user_id_acf928_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['address'], name='blockchain__address_593b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['is_verified'], name='blockchain__is_veri_029bad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together={('user', 'address', 'network')},
        ),
    ]
