# Generated by Django 5.1.7 on 2025-04-22 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_blockchainnetwork_projecttoken_tokentransaction_and_more'),
        ('users', '0005_project_developer_developerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCreationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('total_supply', models.DecimalField(decimal_places=0, max_digits=78)),
                ('admin_address', models.CharField(max_length=255)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deployed', 'Deployed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tokens', to=settings.AUTH_USER_MODEL)),
                ('deployed_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_request', to='blockchain.projecttoken')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_requests', to='blockchain.blockchainnetwork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_requests', to='users.project')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Creation Request',
                'verbose_name_plural': 'Token Creation Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
