# Generated by Django 5.1.7 on 2025-04-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_tokencreationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenredemption',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID of the associated TokenTransaction', max_length=255, null=True),
        ),
    ]
